server:
  port: 8080

spring:
  application:
    name: heuristik
  datasource:
    url: ${POSTGRES_DATASOURCE:jdbc:postgresql://localhost:5432/heuristik_db}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  ai:
    openai:
      api-key: ${OPENAI_KEY}
    ollama:
      embedding:
        enabled: true
        model: paraphrase-multilingual
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}




